### ISSUE TITLE
How do i download and install this module on magisk ?

### ISSUE THREAD

**Issue by aiamuzz** [mrh929/magisk-wifiadb#1]
Hi,

Now that magisk modules are no longer searchable from inside the magisk manager, could you please help me with the procedure to download and install this module on magisk manually ?

thanks.

**Comment by mrh929** [comment]
> Hi,
> 
> Now that magisk modules are no longer searchable from inside the magisk manager, could you please help me with the procedure to download and install this module on magisk manually ?
> 
> thanks.

You can compress these source codes into a zip file, and install it manually in magisk manager.

**Comment by aiamuzz** [comment]
> > Hi,
> > Now that magisk modules are no longer searchable from inside the magisk manager, could you please help me with the procedure to download and install this module on magisk manually ?
> > thanks.
> 
> You can compress these source codes into a zip file, and install it manually in magisk manager.

you mean i download this repo as zip file and install it from within the magisk module ?

My intentions and purposes are to have adbwifi on at all times ... will this module help me achieve that ?

thanks.

**Comment by aiamuzz** [comment]
I downloaded your repo as a zip file and tried installing the module and got the error **'! Unzip error'**

**Comment by mrh929** [comment]
> > You can compress these source codes into a zip file, and install it manually in magisk manager.
> 
> you mean i download this repo as zip file and install it from within the magisk module ?
> 
> My intentions and purposes are to have adbwifi on at all times ... will this module help me achieve that ?
> 
> thanks.

Oh, I know...

The zip file you downloaded from github contains a parent folder, which is not recognized by magisk manager.

You can compress the sources by yourself.

**Comment by mrh929** [comment]
This module just executes a simple shell command and enables wifiadb. If you have any requirement, you can modify whatever you want.

**Comment by aiamuzz** [comment]
> > > You can compress these source codes into a zip file, and install it manually in magisk manager.
> > 
> > 
> > you mean i download this repo as zip file and install it from within the magisk module ?
> > My intentions and purposes are to have adbwifi on at all times ... will this module help me achieve that ?
> > thanks.
> 
> Oh, I know...
> 
> The zip file you downloaded from github contains a parent folder, which is not recognized by magisk manager.
> 
> You can compress the sources by yourself.

i figured that out ... i was able to install it successfully after ... 

thanks for this module.

It would be nice to have found your modules here ... https://www.androidacy.com/magisk-modules-repository/

you must consider submitting it to the above repo ... that way we can download and install directly from the alternate magisk repo.

thanks once again.

PS : after reboot i've been able to connect adb wireless'ly ... I just wanted to know if the Wireless ADB will be ON always, i mean it wouldn't time-out and turn off/Disable ?

**Comment by mrh929** [comment]
> It would be nice to have found your modules here ... https://www.androidacy.com/magisk-modules-repository/
> you must consider submitting it to the above repo ... that way we can download and install directly from the alternate magisk repo.

Thanks for the suggestion, but I think this module is too simple to be submitted to that repository. 😂 I will consider it then.


> PS : after reboot i've been able to connect adb wireless'ly ... I just wanted to know if the Wireless ADB will be ON always, i mean it wouldn't time-out and turn off/Disable ?

Without external process monitoring, WiFiadb should not be able to maintain its status. If the Android system shuts down the WiFi adb feature, it will not restart. I am considering writing a process to monitor the system’s WiFi adb status and restart it when necessary. 

And when this module is turned off by magisk manager, I think I can also shut down WiFi adb feature, just like https://github.com/taamarin/ClashforMagisk 😂.

**Comment by aiamuzz** [comment]
> I am considering writing a process to monitor the system’s WiFi adb status and restart it when necessary.

Hey, that would really be great ... look forward to this development.

> Thanks for the suggestion, but I think this module is too simple to be submitted to that repository.  I will consider it then.

Please don't shy away even if its few lines of code, it is really a nifty feature to have, your module is certainly better than having to install a separate app to gain the same functionality.

**Comment by mrh929** [comment]
Added feature in #3

**Comment by aiamuzz** [comment]
> Added feature in #3

@mrh929 ...
Wow ... thanks ... that was quick ... i just need to re-install the zip file as before ?
I had to reattach the cable and fire a adb reboot just so your wifiadb is running ... this feature means i need not connect the cable right ?

this feature [(restart wifiadb)](https://github.com/mrh929/magisk-wifiadb/pull/3/commits/011d2c3d0a4e3cc4ebd19ae8c3bae11286f8a00d), how frequently will it check for the wifiadb's **'running'** status and initiate a restart command ?

**Comment by mrh929** [comment]
> > Added feature in #3
> 
> @mrh929 ... Wow ... thanks ... that was quick ... i just need to re-install the zip file as before ? I had to reattach the cable and fire a adb reboot just so your wifiadb is running ... this feature means i need not connect the cable right ?
> 
> this feature [(restart wifiadb)](https://github.com/mrh929/magisk-wifiadb/pull/3/commits/011d2c3d0a4e3cc4ebd19ae8c3bae11286f8a00d), how frequently will it check for the wifiadb's **'running'** status and initiate a restart command ?

5 secs. If you are curious about it, just go through the source file in https://github.com/mrh929/magisk-wifiadb/blob/507269e03d921f3d202dabeeff208aa523477e15/common/service.sh.

**Comment by aiamuzz** [comment]
> > > Added feature in #3
> > 
> > 
> > @mrh929 ... Wow ... thanks ... that was quick ... i just need to re-install the zip file as before ? I had to reattach the cable and fire a adb reboot just so your wifiadb is running ... this feature means i need not connect the cable right ?
> > this feature [(restart wifiadb)](https://github.com/mrh929/magisk-wifiadb/pull/3/commits/011d2c3d0a4e3cc4ebd19ae8c3bae11286f8a00d), how frequently will it check for the wifiadb's **'running'** status and initiate a restart command ?
> 
> 5 secs. If you are curious about it, just go through the source file in https://github.com/mrh929/magisk-wifiadb/blob/507269e03d921f3d202dabeeff208aa523477e15/common/service.sh.

ya, ... i did read the source code and saw `sleep 5` and assumed that must've been the frequency ... but i wanted to be sure hence the question ... Is there no burden on the resources to be checking the status every 5 secs ?

**Comment by mrh929** [comment]
> ya, ... i did read the source code and saw `sleep 5` and assumed that must've been the frequency ... but i wanted to be sure hence the question ... Is there no burden on the resources to be checking the status every 5 secs ?

Don't worry about that... An APK will consume much more resources if it checks the status of WiFi ADB frequently...

**Comment by aiamuzz** [comment]
ok let me share the reason ...

My yearning for a feature as provided by your module/script was because my device has a blacked out(cracked) screen, as i was aware of wireless debugging from having used custom ROMS(right from my first set of android's ... i started looking for the same in a stock ROM(Oneplus's Oxygen OS) ... my only unmodded(ROM wise) device I've ever used.

the lack of Wireless Debugging in the stock Oxygen ROM prompted me to hunt for a solution that was inherent to a custom ROM is when i happen to land at your doorsteps ... and have been using it since ... thanks to you now with the always ON wifiadb you've recently added ... my life has all the more become easier ...

**With the latest feature addition this always-ON wifiadb is equivalent to the wireless debugging option(with this now any stock ROM with Magisk can enjoy the feature of wireless debugging) found on the custom ROMS's**

**Comment by mrh929** [comment]
> ok let me share the reason ...
> 
> My yearning for a feature as provided by your module/script was because my device has a blacked out(cracked) screen, as i was aware of wireless debugging from having used custom ROMS(right from my first set of android's ... i started looking for the same in a stock ROM(Oneplus's Oxygen OS) ... my only unmodded(ROM wise) device I've ever used.
> 
> the lack of Wireless Debugging in the stock Oxygen ROM prompted me to hunt for a solution that was inherent to a custom ROM is when i happen to land at your doorsteps ... and have been using it since ... thanks to you now with the always ON wifiadb you've recently added ... my life has all the more become easier ...
> 
> **With the latest feature addition this always-ON wifiadb is equivalent to the wireless debugging option(with this now any stock ROM with Magisk can enjoy the feature of wireless debugging) found on the custom ROMS's**

I'm glad that the script I wrote provides you with such a great convenience 😄 . 

And I am curious when will WiFi ADB be turned off? I have a pixel 2, but WiFi ADB is always on. 
Now this module is monitoring the environment variable "service.adb.tcp.port". Once it changes to null, WiFi ADB have to get restarted. 
Is there any corner case?
