### ISSUE TITLE
Compatible with Android 14+?

### ISSUE THREAD

**Issue by jhlee2222** [mrh929/magisk-wifiadb#26]
Is this module only compatible with certain Android versions?

I've got it successfully working on some older Android devices, but two I'm trying it with, running Android 14 and Android 13 respectively, don't seem to accept the module. Magisk will appear to install it, but then after rebooting the module doesn't appear to do anything and is not available in the list of modules to enable/disable in Magisk.

**Comment by nenahp** [comment]
Try with a14 (ksu), seems not work for me...


**EDIT:**
Try again, it works on 5555 port
https://github.com/mrh929/magisk-wifiadb//blob/38d0d1be3d2d537ab7e7ce37e1693b62896dc232/common/service.sh#L20...
I just misuse a random port scan scripts again.

**Comment by jhlee2222** [comment]
For me, it's that the module appears to install, then it's not available in Magisk to toggle on or off with my other modules.

**Comment by jhlee2222** [comment]
This is what I see when I install the module with Magisk:
![Screenshot_20241222-223946](https://github.com/user-attachments/assets/8a3e0751-9089-4519-a5e4-e8bab9091230)

However, when I reboot, the module isn't there in my list of modules. I'm on the Canary release of Magisk, 28101.

**Comment by jhlee2222** [comment]
After some experimentation, I believe I've confirmed the compatibility issue I'm seeing is not with the Android version, but the version of Magisk used. I set up a newer device on Android 14, this time opting for Magisk 26.3. The module installs, shows up in the list, and frankly, works! 

Is there any way the module can be updated to work with newer versions of Magisk?

**Comment by jhlee2222** [comment]
Closing issue as it is not a matter of compatibility with later versions of Android, but with later versions of Magisk. See issue:
https://github.com/mrh929/magisk-wifiadb/issues/27
