### ISSUE TITLE
Disable WiFi ADB in Magisk Manager

### ISSUE THREAD

**Issue by mrh929** [mrh929/magisk-wifiadb#5]

**Comment by aiamuzz** [comment]
@mrh929 ...

would it be too much efforts to have a quick settings button for this module rather than open the magisk app and enable / disable the module (which requires one to reboot the phone to take effect)?

When the button is enabled it should run as it does (including the newly added always on wifiadb feature)
When the button is long pressed ... it can provide the user to configure the [adb port](https://github.com/mrh929/magisk-wifiadb/issues/4)
When the button is disabled it can turn wifiadb off.

**Comment by mrh929** [comment]
> would it be too much efforts to have a quick settings button for this module rather than open the magisk app and enable / disable the module (which requires one to reboot the phone to take effect)?

I think it is impossible because a buttom requires to be registered in an APK, which is what [WiFiADB](https://play.google.com/store/apps/details?id=com.ttxapps.wifiadb&hl=en&gl=US) does...

However, I have previously used magisk-clash, and it is capable of immediately enabling or disabling its functionality when I click the switch button in Magisk Manager. I am curious about how it accomplishes this. This feature is much more efficient compared to modifying the Magisk module configuration and then rebooting.

**Comment by aiamuzz** [comment]
> However, I have previously used magisk-clash, and it is capable of immediately enabling or disabling its functionality when I click the switch button in Magisk Manager. I am curious about how it accomplishes this. This feature is much more efficient compared to modifying the Magisk module configuration and then rebooting.

oh ... what is this magisk-clash ... ?

I am of the understanding that any module when enabled / disabled from the within the magisk modula manager needs to reboot to take effect ... isn't it so ?

**Comment by mrh929** [comment]
> > However, I have previously used magisk-clash, and it is capable of immediately enabling or disabling its functionality when I click the switch button in Magisk Manager. I am curious about how it accomplishes this. This feature is much more efficient compared to modifying the Magisk module configuration and then rebooting.
> 
> oh ... what is this magisk-clash ... ?

It is a transport layer proxy to bypass the firewall. 

> I am of the understanding that any module when enabled / disabled from the within the magisk modula manager needs to reboot to take effect ... isn't it so ?

Maybe it uses some tricks, like writing files and monitoring files. Magisk is free enough for developers to do anything they want.

**Comment by aiamuzz** [comment]
so can i enable disable wifiadb(without having to reboot) with the currently installed module ?
If yes please guide me through the steps.

**Comment by mrh929** [comment]
> so can i enable disable wifiadb(without having to reboot) with the currently installed module ? If yes please guide me through the steps.

You can check the source file [service.sh](https://github.com/mrh929/magisk-wifiadb/blob/507269e03d921f3d202dabeeff208aa523477e15/common/service.sh). This module has many template files, but core code consists of only a few dozen lines.

**Comment by aiamuzz** [comment]
> > so can i enable disable wifiadb(without having to reboot) with the currently installed module ? If yes please guide me through the steps.
> 
> You can check the source file [service.sh](https://github.com/mrh929/magisk-wifiadb/blob/507269e03d921f3d202dabeeff208aa523477e15/common/service.sh). This module has many template files, but core code consists of only a few dozen lines.

oh ... you mean the commands ...

```
stop adbd
start adbd
```
is how i can enable disable it ?

**Comment by mrh929** [comment]
> > > so can i enable disable wifiadb(without having to reboot) with the currently installed module ? If yes please guide me through the steps.
> > 
> > 
> > You can check the source file [service.sh](https://github.com/mrh929/magisk-wifiadb/blob/507269e03d921f3d202dabeeff208aa523477e15/common/service.sh). This module has many template files, but core code consists of only a few dozen lines.
> 
> oh ... you mean the commands ...
> 
> ```
> stop adbd
> start adbd
> ```
> 
> is how i can enable disable it ?

And a setprop command is also necessary.

These commands requires to be execute at the same time, or you will disconnect from adb before you are able to restart it. This is why I let them run in the backgroud.

**Comment by aiamuzz** [comment]
> or you will disconnect from adb before you are able to restart it.

hahahaha ... i did end up here ... with even the wired adb lost ... took a lot of effort flying blind to reboot my phone ... with an even BIGGER worry that I may have disabled ADB altogether(WHICH WOULD HAVE MADE MY SCREENLESS PHONE USELESS) ... but a reboot thankfully brought back wired adb and then i could connect through your script/module.

**Comment by mrh929** [comment]
This feature is added in #6 .
